#!/usr/bin/env python3
"""Vansiwala Dresses - catalog generator.

Scans assets/products/ for images and builds products.json (editable config)
plus assets/js/data.js (bundled data so the site also works via file://).

Run:  python3 tools/generate_products.py
After editing products.json, run this again to refresh data.js.
"""
import json
import os
import re

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
IMG_DIR = os.path.join(ROOT, "assets", "products")
JSON_PATH = os.path.join(ROOT, "products.json")
DATA_JS_PATH = os.path.join(ROOT, "assets", "js", "data.js")

WHATSAPP = "919625979355"
CURRENCY = "₹"

CATEGORIES = [
    {"id": "bal-gopal-poshak", "name": "Bal Gopal Poshak"},
    {"id": "khatu-shyam", "name": "Khatu Shyam Ji Outfits"},
    {"id": "accessories", "name": "Accessories"},
    {"id": "handmade-special", "name": "Handmade Special"},
]

TITLE_POOL = [
    "Handmade Designer Bal Gopal Poshak",
    "Royal Stitched Poshak with Zari Work",
    "Premium Velvet Poshak Set",
    "Traditional Silk Poshak with Motifs",
    "Handcrafted Khatu Shyam Ji Outfit",
    "Festive Special Handmade Poshak",
    "Deity Poshak with Golden Borders",
    "Designer Shringar Poshak Set",
]

PRICE_POOL = [1499, 1799, 1999, 2499, 2999, 3499, 3999, 4499]

IMG_RE = re.compile(r"\.(jpe?g|png|webp|avif)$", re.IGNORECASE)


def scan_images():
    files = []
    for name in sorted(os.listdir(IMG_DIR)):
        if IMG_RE.search(name):
            files.append(name)
    return files


def load_existing():
    if os.path.exists(JSON_PATH):
        with open(JSON_PATH, encoding="utf-8") as fh:
            return json.load(fh)
    return None


def build_catalog():
    images = scan_images()
    existing = load_existing()
    catalog = {}
    if existing:
        for p in existing.get("products", []):
            catalog[p["image"]] = p

    cat_ids = [c["id"] for c in CATEGORIES]
    products = []
    for idx, image in enumerate(images):
        if image in catalog:
            products.append(catalog[image])
            continue
        products.append({
            "id": idx + 1,
            "name": TITLE_POOL[idx % len(TITLE_POOL)],
            "category": cat_ids[idx % len(cat_ids)],
            "price": PRICE_POOL[idx % len(PRICE_POOL)],
            "image": image,
            "warranty": True,
        })

    return {
        "brand": "Vansiwala Dresses",
        "tagline": "Handcrafted Elegance for Bal Gopal & Deities",
        "currency": CURRENCY,
        "whatsapp": WHATSAPP,
        "hero": {"image": "", "title": "Handcrafted Elegance for Bal Gopal & Deities"},
        "categories": CATEGORIES,
        "products": products,
    }


def main():
    catalog = build_catalog()
    with open(JSON_PATH, "w", encoding="utf-8") as fh:
        json.dump(catalog, fh, ensure_ascii=False, indent=2)

    js = "/* Auto-generated by tools/generate_products.py. Edit products.json and re-run. */\n"
    js += "window.VANSIWALA_DATA = " + json.dumps(catalog, ensure_ascii=False, indent=2) + ";\n"
    with open(DATA_JS_PATH, "w", encoding="utf-8") as fh:
        fh.write(js)

    print(f"products.json  -> {len(catalog['products'])} products")
    print(f"data.js        -> {os.path.relpath(DATA_JS_PATH, ROOT)}")


if __name__ == "__main__":
    main()
