#!/usr/bin/env python3
"""Vansiwala Dresses — local dev server.

Serves the site AND lets the hidden edit mode save changes back to
products.json + assets/js/data.js.

Run:
    /usr/bin/python3 tools/server.py
Then open:  http://localhost:8080
Edit mode:  http://localhost:8080/#edit
"""
import json
import os
import sys
from http.server import HTTPServer, SimpleHTTPRequestHandler

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
JSON_PATH = os.path.join(ROOT, "products.json")
DATA_JS_PATH = os.path.join(ROOT, "assets", "js", "data.js")
PORT = 8080


def write_catalog(catalog):
    with open(JSON_PATH, "w", encoding="utf-8") as fh:
        json.dump(catalog, fh, ensure_ascii=False, indent=2)
    js = (
        "/* Auto-generated by tools/server.py from products.json. */\n"
        "window.VANSIWALA_DATA = "
        + json.dumps(catalog, ensure_ascii=False, indent=2)
        + ";\n"
    )
    with open(DATA_JS_PATH, "w", encoding="utf-8") as fh:
        fh.write(js)


class Handler(SimpleHTTPRequestHandler):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, directory=ROOT, **kwargs)

    def do_POST(self):
        if self.path.rstrip("/") == "/api/save":
            length = int(self.headers.get("Content-Length", 0))
            raw = self.rfile.read(length)
            try:
                catalog = json.loads(raw.decode("utf-8"))
                if "products" not in catalog:
                    raise ValueError("missing products")
            except Exception as exc:  # noqa: BLE001
                self.send_error(400, "Invalid JSON: %s" % exc)
                return
            try:
                write_catalog(catalog)
            except Exception as exc:  # noqa: BLE001
                self.send_error(500, "Write failed: %s" % exc)
                return
            body = b'{"ok":true}'
            self.send_response(200)
            self.send_header("Content-Type", "application/json")
            self.send_header("Content-Length", str(len(body)))
            self.end_headers()
            self.wfile.write(body)
        else:
            self.send_error(404)

    def log_message(self, fmt, *args):
        sys.stderr.write("[vansiwala] %s - %s\n" % (self.address_string(), fmt % args))


if __name__ == "__main__":
    print("Vansiwala Dresses — serving at http://localhost:%d" % PORT)
    print("Edit mode: http://localhost:%d/#edit" % PORT)
    try:
        HTTPServer(("0.0.0.0", PORT), Handler).serve_forever()
    except KeyboardInterrupt:
        print("\nStopped.")
